# Generated by Django 2.2.4 on 2020-12-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
        ('questions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_category', to='questions_app.Category')),
                ('quiz_taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_details', to='login_app.User')),
            ],
        ),
    ]
